refactored to handle registerDeferredDeepLinkHandler before startSession
mparticle-integrations/mparticle-apple-integration-singular pull request #4
Opened 2017-08-21 11:26 UTC by anismiles

2017-08-21 22:33 UTC, samdozor requested changes

2017-08-21 22:33 UTC, samdozor commented on mParticle-Singular/MPKitSingular.m
> +            ddlLink = [[NSDictionary alloc] initWithObjectsAndKeys:deeplink,SINGULAR_DEEPLINK_KEY, nil];
@anismiles you should be invoking the deep link completion handler here, if not nil

2017-08-21 22:33 UTC, samdozor commented on mParticle-Singular/MPKitSingular.m
> +    NSDictionary *ddlLink;
Can you also add a property for the deep link completion handler that's passed into the kit from the implementing app?

2017-08-21 22:33 UTC, samdozor commented on mParticle-Singular/MPKitSingular.m
> +    if (_started && (ddlLink)){
if neither of these are true, you should be saving a reference to the completion handler for later use.

2017-08-21 22:33 UTC, samdozor commented on mParticle-Singular/MPKitSingular.m
> +            ddlLink = [[NSDictionary alloc] initWithObjectsAndKeys:deeplink,SINGULAR_DEEPLINK_KEY, nil];
similar to during kit initialization, you should be invoking the completion handler property here.

2017-08-21 22:33 UTC, samdozor commented on mParticle-Singular/MPKitSingular.m
> +            ddlLink = [[NSDictionary alloc] initWithObjectsAndKeys:deeplink,SINGULAR_DEEPLINK_KEY, nil];
same comment as above regarding completion handler

2017-08-21 22:33 UTC, samdozor commented on mParticle-Singular/MPKitSingular.m
> +            ddlLink = [[NSDictionary alloc] initWithObjectsAndKeys:deeplink,SINGULAR_DEEPLINK_KEY, nil];
same comment as above.

2017-08-22 10:22 UTC, anismiles commented on mParticle-Singular/MPKitSingular.m
> +    NSDictionary *ddlLink;
Done.

2017-08-22 10:22 UTC, anismiles commented on mParticle-Singular/MPKitSingular.m
> +    if (_started && (ddlLink)){
Done.

2017-08-22 13:24 UTC, samdozor approved these changes
LGTM! Thanks @anismiles

2017-08-22 13:24 UTC, merged